import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className={inter.className}>
        <div className="bg-[#f8f6f6]">
          <Header />
          {children}
          <Footer />
        </div>
=======
      <body suppressHydrationWarning={true} className={inter.className}>
        <Header />
        {children}
        <Footer />
>>>>>>> 263c667123cd85c277f49f9ec88c80a3de09bfc7
      </body>
    </html>
  );
}
