export const paths = {
  home: "/",
  information: {
    introduction: "/about#Introduction",
    nature_of_the_organization: "/about#Nature of the organization",
    arena_limits: "/about#Arena limits",
    aims_and_objectives: "/about#Aims and Objectives",
    slogan: "/about#Slogan",
    vision: "/about#Vision",
    structure: "/structure",
  },
  activites: {
    human_needs: "/#activities",
    education: "/#activities",
    health: "/#activities",
    training: "/#activities",
    the_culture: "/#activities",
    awareness: "/#activities",
  },
  campaign: "/#campagin",
  news: "/news",
  registration: {
    volunteer: "/contact",
    ordinary_member: "/contact",
    lifetime_member: "/contact",
    donor_member: "/contact",
  },
  donate: "/donate",
  contact: "/contact",
};
